spring:
  datasource:
    url: jdbc:mysql://springboard-database-1.c4nr3osbeo7h.ap-northeast-2.rds.amazonaws.com:3306/MyBoardDatabase
    username: admin
    password:

    #url: jdbc:h2:tcp://localhost/~/springboard
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

file:
  dir: /home/ubuntu/savefile/
  #dir: E:\savefile\



fcm:
  key:
    path: boardfcm-4f2b0-firebase-adminsdk-hee5n-d62e26d428.json
    scope: https://www.googleapis.com/auth/cloud-platform

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

#  spring.datasource.url=jdbc:mysql://나의엔드포인트:3306/DB이름(mydatabase)
#  spring.datasource.username=마스터 이름
#  spring.datasource.password=마스터 암호
#  spring.jpa.hibernate.ddl-auto=update